[project]
name = "tgram"
version = "1.10.3"
authors = [
  { name="ZAID", email="me@zaid.pro" },
]
description = "Very friendly BOT API library for python devs."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp==3.9.4",
  "asyncio",
]

[project.urls]
Homepage = "https://github.com/2ei/tgram"
Issues = "https://github.com/2ei/tgram/issues"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["tgram*"]
exclude = ["docs*", "tests*", "examples*"]
